sudo: required

services:
    - docker

before_install:
    - docker build -t deepakdavisc/docker-react -f Dockerfile.dev .

scripts:
    -  docker run deepakdavisc/docker-react npm run test -- --coverage
