sudo: required

services:
    - docker

before_install:
    - echo "BEFORE INSTALL START"
    - gem install bundler
    - echo "BEFORE INSTALL END"
    - docker build -t deepakdavisc/docker-react -f Dockerfile.dev .

scripts:
    -  docker run deepakdavisc/docker-react npm run test -- --coverage
